### ISSUE TITLE
Locally hosted FAS in Docker firewall issue 

### ISSUE THREAD

**Issue by trueToastedCode** [openNDS/openNDS#564]
I have a nodejs server 'my-fas' hosted at 0.0.0.0:2080 in a Docker container

**docker-compose.yml**
```
version: '3.9'
services:
  my-fas:
    image: truetoastedcode/my-fas
    container_name: my-fas
    network_mode: "host"
    ports:
      - '2080:2080'
```
I have set up a wifi hotspot with dnsmasq and hostapd, which works fine (can connect, have internet access and can visit my-fas while opennds not running).
```
iptables -t nat -A POSTROUTING -o enp0s5 -j MASQUERADE
iptables -A FORWARD -i enp0s5 -o wlx503eaa75dfcc -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlx503eaa75dfcc -o enp0s5 -j ACCEPT
sysctl net.ipv4.ip_forward=1
ip link set wlx503eaa75dfcc down
ip address add 192.168.5.1/24 dev wlx503eaa75dfcc
ip link set wlx503eaa75dfcc up
service dnsmasq start
service hostapd start
```
However as soon as I also start the opennds service, I cannot access my fas anymore from connected devices anymore (still works on the host machine). It works again, when stopping the service. 
**opennds config**
```
option gatewayinterface 'wlx503eaa75dfcc'
option fasport '2080'
option fas_secure_enabled '0'
```
